name: windows

on:
  push:
    branches:
      - 2.x
  pull_request:
    branches:
      - 2.x
      - "!v[0-9]*"

# Remove default permissions of GITHUB_TOKEN for security
# https://docs.github.com/en/actions/using-jobs/assigning-permissions-to-jobs
permissions: {}

concurrency:
  group: ${{ github.workflow }}-${{ github.event.number || github.sha }}
  cancel-in-progress: ${{ github.event_name != 'push' }}

jobs:
  setup:
    runs-on: ${{ matrix.os }}
    if: github.event_name == 'push' || !((github.base_ref == '2.x') && github.head_ref == 'dev')

    strategy:
      matrix:
        os: [windows-latest]

    steps:
      - uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4.1.1
      - run: corepack enable
      - uses: actions/setup-node@60edb5dd545a775178f52524783378180af0d1f8 # v4.0.2
        with:
          node-version: 18
          cache: "yarn"

      - name: install
        run: yarn --check-files --frozen-lockfile --non-interactive

      - name: cache workspace
        uses: actions/cache@0c45773b623bea8c8e75f6c82b208c3cf94ea4f9 # v4.0.2
        with:
          path: |
            node_modules
            packages/*/node_modules
            distributions/*/node_modules
            packages/*/dist
          key: ${{ matrix.os }}-node-v18-nuxt-${{ github.sha }}

  test-unit:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [windows-latest]

    env:
      NODE_OPTIONS: "--max_old_space_size=4096"

    steps:
      - uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4.1.1
      - run: corepack enable
      - uses: actions/setup-node@60edb5dd545a775178f52524783378180af0d1f8 # v4.0.2
        with:
          node-version: 18
          cache: "yarn"

      - name: restore workspace cache
        uses: actions/cache@0c45773b623bea8c8e75f6c82b208c3cf94ea4f9 # v4.0.2
        with:
          path: |
            node_modules
            packages/*/node_modules
            distributions/*/node_modules
            packages/*/dist
          key: ${{ matrix.os }}-node-v18-nuxt-${{ github.sha }}

      - name: test unit
        run: yarn test:unit --testPathIgnorePatterns=packages/cli

    needs: setup

  build:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [windows-latest]

    env:
      NODE_OPTIONS: "--max_old_space_size=4096"

    steps:
      - uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4.1.1
      - run: corepack enable
      - uses: actions/setup-node@60edb5dd545a775178f52524783378180af0d1f8 # v4.0.2
        with:
          node-version: 18
          cache: "yarn"

      - name: restore workspace cache
        uses: actions/cache@0c45773b623bea8c8e75f6c82b208c3cf94ea4f9 # v4.0.2
        with:
          path: |
            node_modules
            packages/*/node_modules
            distributions/*/node_modules
            packages/*/dist
          key: ${{ matrix.os }}-node-v18-nuxt-${{ github.sha }}

      - name: build
        run: yarn test:fixtures

      - name: Save fixtures
        uses: actions/upload-artifact@5d5d22a31266ced268874388b861e4b58bb5c2f3 # v4.3.1
        with:
          name: fixtures-${{ matrix.os }}-node-v18
          path: test/fixtures
    needs: setup

  test-dev:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [windows-latest]

    env:
      NODE_OPTIONS: "--max_old_space_size=4096"

    steps:
      - uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4.1.1
      - run: corepack enable
      - uses: actions/setup-node@60edb5dd545a775178f52524783378180af0d1f8 # v4.0.2
        with:
          node-version: 18
          cache: "yarn"

      - name: restore workspace cache
        uses: actions/cache@0c45773b623bea8c8e75f6c82b208c3cf94ea4f9 # v4.0.2
        with:
          path: |
            node_modules
            packages/*/node_modules
            distributions/*/node_modules
            packages/*/dist
          key: ${{ matrix.os }}-node-v18-nuxt-${{ github.sha }}

      - name: restore fixtures
        uses: actions/download-artifact@c850b930e6ba138125429b7e5c93fc707a7f8427 # v4.1.4
        with:
          name: fixtures-${{ matrix.os }}-node-v18
          path: test/fixtures

      - name: test dev
        run: yarn test:dev
    needs: build
